{% set version = "3.3.0" %}

package:
  name: pydap
  version: {{ version }}

source:
  url: https://github.com/pydap/pydap/archive/refs/tags/{{ version }}.tar.gz
  sha256: 566ba4a12a47547135c46324ddc65b03e680ec007f01581ceca0b0341d2110b0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - pydap = pydap.wsgi.app:main
    - dods = pydap.handlers.dap:dump

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - beautifulsoup4
    - docopt
    - jinja2
    - numpy
    - webob
    - six >=1.4.0
    - webob
    #  net
    - requests

test:
  imports:
    - pydap
  requires:
    - gunicorn  # [not win]
    - pastedeploy  # [not win]
    - pip
  commands:
    - pydap -h  # [not win]
  commands:
    - pip check

about:
  home: http://pydap.org/
  license: MIT
  license_file: docs/license.rst
  summary: 'Pure Python Opendap/DODS client and server'

extra:
  recipe-maintainers:
    - ocefpaf
